project:
  type: website

website:
  title: "Fun With Numbers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto